name: Terraform plan


on:
    pull_request:
      branches:
        - main


env:
    AWS_REGION: "us-east-1"
    tf_actions_working_dir: ./terraform

jobs:
    Creating-terraform-plan:
        runs-on: ubuntu-latest
        defaults:
            run:
              working-directory: ${{ env.tf_actions_working_dir }}
        permissions:
            id-token: write   # This is required for requesting the JWT
            contents: read    # This is required for actions/checkout
            pull-requests: write
        steps:
            - name: cloning the repo
              uses: actions/checkout@v4


            - name: configure aws credentials
              uses: aws-actions/configure-aws-credentials@v3
              with:
                role-to-assume: arn:aws:iam::746196583728:role/sample-ga-role
                role-session-name: sample-ga-role
                aws-region: ${{ env.AWS_REGION }}


            - name: terraform setup
              uses: hashicorp/setup-terraform@v3

            - name: Terraform fmt
              id: fmt
              run: terraform fmt -check
              continue-on-error: true
            
            - name: Terraform Init
              id: init
              run: terraform init
            
            - name: Terraform Validate
              id: validate
              run: terraform validate -no-color
            
            - name: Terraform Plan
              id: plan
              run: terraform plan -no-color
              continue-on-error: true
            
            - uses: actions/github-script@v7
              if: github.event_name == 'pull_request'
              env:
                    PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
                  with:
                    github-token: ${{ secrets.GITHUB_TOKEN }}
                    script: |
                      const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
                      #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
                      #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
                      <details><summary>Validation Output</summary>
                
                      \`\`\`\n
                      ${{ steps.validate.outputs.stdout }}
                      \`\`\`
                
                      </details>
                
                      #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
                
                      <details><summary>Show Plan</summary>
                
                      \`\`\`\n
                      ${process.env.PLAN}
                      \`\`\`
                
                      </details>
                
                      *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;
                
                      github.rest.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: output
                      })