name: Test workflow

on: push

jobs:
    create-file-job:
        runs-on: ubuntu-latest
        steps:
            - name: cloning step
              uses: actions/checkout@v4

            - name: Create a directory and file
              run: |
                    mkdir -p ./play-dir/custom-file
                    ls .
                    ls ./play-dir